apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      kubernetes.io/name: "Metrics-server"
      kubernetes.io/cluster-service: "true"
